inherit_from: https://raw.githubusercontent.com/discourse/discourse/master/.rubocop.yml
require: rubocop-performance
AllCops:
  TargetRubyVersion: 2.4
  DisabledByDefault: true
  Exclude:
    - 'spec/**/**/*.rb'
